[context.master]
  environment = { VUE_APP_API_URL="https://hwealth.me/api" }

[context.dev]
  environment = { VUE_APP_API_URL="https://hwealth.herokuapp.com/api" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src https:; script-src https: 'unsafe-inline'; style-src https: 'unsafe-inline'; object-src 'none'"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; microphone 'none'; camera 'none'; speaker 'none';"